name: Build Windows x64

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:

permissions: 
  contents: write
  
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
        runtime: [ 'win-x64' ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore -r ${{ matrix.runtime }} --locked-mode
      - name: Publish
        run: dotnet publish -r ${{ matrix.runtime }} -c Release -o ./publish ./src/TMSpeech/TMSpeech.csproj
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: TMSpeech.${{ matrix.runtime }}
          path: publish/
  # when tag is pushed and starts with 'v', create a release using the artifacts
  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: TMSpeech.win-x64
          path: app
      - name: Create ZIP
        run: Compress-Archive -Path app/* -DestinationPath TMSpeech.win-x64.zip
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            TMSPeech.win-x64.zip
          generate_release_notes: true
